<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="16708" started-at="2019-01-11T13:25:34Z" finished-at="2019-01-11T13:25:51Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="16708" started-at="2019-01-11T13:25:34Z" finished-at="2019-01-11T13:25:51Z">
      <class name="script.FbLogin">
        <test-method status="PASS" signature="initFrameWork()[pri:0, instance:script.FbLogin@43738a82]" name="initFrameWork" is-config="true" duration-ms="5" started-at="2019-01-11T13:25:34Z" finished-at="2019-01-11T13:25:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initFrameWork -->
        <test-method status="PASS" signature="openApp(java.lang.String)[pri:0, instance:script.FbLogin@43738a82]" name="openApp" is-config="true" duration-ms="8571" started-at="2019-01-11T13:25:34Z" finished-at="2019-01-11T13:25:43Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method status="FAIL" signature="testFbLogin()[pri:0, instance:script.FbLogin@43738a82]" name="testFbLogin" duration-ms="7380" started-at="2019-01-11T13:25:43Z" finished-at="2019-01-11T13:25:50Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at script.FbLogin.testFbLogin(FbLogin.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFbLogin -->
        <test-method status="PASS" signature="closeApp()[pri:0, instance:script.FbLogin@43738a82]" name="closeApp" is-config="true" duration-ms="72" started-at="2019-01-11T13:25:51Z" finished-at="2019-01-11T13:25:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- script.FbLogin -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
